# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: CI/CD Test Web Application
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]

    steps:
    - name: Installing the packages -> Jest
      run: npm install --save-dev jest 
      
    - name: Installing the packages -> Puppeteer
      run: npm i puppeteer
    
    - name: Run the ci for last packages
      run: npm ci
      
    - name: Running the tests
      run: npm test
