# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: CI/CD Test Web Application
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]

    steps:
    - name: Checkout code
    - uses: actions/checkout@v2
    
    - name: Use Node.js ${{ matrix.node-version }} for installing Pup and Jest
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm i puppeteer
    - run: npm install --save-dev jest
    
    - name: Building the project 
    - run: npm run build --if-present
    
    - name: Running the tests
    - run: npm test
